---
- name: Install docker, python and pip
  hosts: test
  become: yes
  gather_facts: false
 
  tasks: 
    - name: Install docker packages
      remote_user: ubuntu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-pip
        - python-setuptools
      tags:
        - docker
    
    - name: Add Docker's official GPG key
      remote_user: ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify that we have the key with the fingerprint
      remote_user: ubuntu
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker
    
    - name: Set up the stable repository
      remote_user: ubuntu
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Update apt packages
      remote_user: ubuntu
      apt:
        update_cache: yes
      tags:
        - docker
    
    - name: Install docker
      remote_user: ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker
    
    - name: Add remote "ubuntu" user to "docker" group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker
    
    - name: Install docker-compose
      remote_user: ubuntu
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
   
    - name: Install virtualenv for python
      pip:     
        name: "virtualenv"
        state: present

    - name: Install docker module for python
      pip:
        name: "docker"
        state: present
      
    - name: Be sure docker directory exists
      file:
        path: "/home/ubuntu/.docker"
        state: directory

  roles:
    - role: ansible-role-node_exporter
